language: node_js
node_js: 8
dist: bionic
cache:
  npm: true
  directories:
  - $HOME/.local/share/flatpak
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

env:
  global:
  - DEBUG: electron-installer-flatpak,@malept/flatpak-bundler

before_install:
- sudo add-apt-repository -y ppa:alexlarsson/flatpak
- sudo apt update
- sudo apt install --no-install-recommends -y flatpak-builder
- ./test/install_runtimes.sh

install:
- npm install
- npm update

script: npm run ci
after_success: npm run codecov
